<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>MAP.C.Runtime</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\MAP.C.Contract\MAP.C.Contract.csproj" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Database\db-api.json" />
  </ItemGroup>

</Project>
