<Project Sdk="Microsoft.NET.Sdk.Razor">
  <Import Project="..\..\Sdk\MAP.ModuleSdk.props" />
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>MAP.M.Template</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Components.Web" />
    <PackageReference Include="Radzen.Blazor" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Localization\vi.json" LogicalName="MAP.M.Template.Localization.vi.json" />
    <EmbeddedResource Include="Localization\en.json" LogicalName="MAP.M.Template.Localization.en.json" />
    <Content Remove="Localization\**" />
  </ItemGroup>
</Project>
