<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>MAP.C.Wasm</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\MAP.C.Contract\MAP.C.Contract.csproj" />
    <ProjectReference Include="..\MAP.C.Runtime\MAP.C.Runtime.csproj" />
  </ItemGroup>

</Project>
