<Project Sdk="Microsoft.NET.Sdk.Razor">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Components.Web" />
    <PackageReference Include="Radzen.Blazor" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Core\MAP.C.Contract\MAP.C.Contract.csproj" PrivateAssets="all" />
    <ProjectReference Include="..\..\Core\MAP.C.UI\MAP.C.UI.csproj" PrivateAssets="all" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Localization\vi.json" LogicalName="MAP.M.Home.Localization.vi.json" />
    <EmbeddedResource Include="Localization\en.json" LogicalName="MAP.M.Home.Localization.en.json" />
    <Content Remove="Localization\**" />
  </ItemGroup>

</Project>
